/*
 *
 * App actionTypes
 *
 */

export const TAKE_PICTURE_REQUEST = 'SKT_PIC_REQUEST';
export const TAKE_PICTURE_RESPONSE = 'TK_PIC_RESPONSE';

export const CHECK_STATUS_REQUEST = 'SKT_STA_REQUEST';
export const CHECK_STATUS_RESPONSE = 'TK_STA_RESPONSE';

export const VERIFY_BATTERY_REQUEST = 'SKT_VBA_REQUEST';
export const VERIFY_BATTERY_RESPONSE = 'TK_VBA_RESPONSE';

export const GET_CAMERA_MEDIA = 'GET_CAMERA_MEDIA';
export const DELETE_PICTURE = 'DELETE_PICTURE';

// Global error
export const APP_GLOBAL_ERROR = "APP_GLOBAL_ERROR";
