/*
 *
 * App actionTypes
 *
 */

export const TAKE_PICTURE_REQUEST = 'SKT_PIC_REQUEST';
export const TAKE_PICTURE_RESPONSE = 'TK_PIC_RESPONSE';

export const CHECK_STATUS_REQUEST = 'SKT_STA_REQUEST';
export const CHECK_STATUS_RESPONSE = 'TK_STA_RESPONSE';

export const GET_CAMERA_MEDIA = 'GET_CAMERA_MEDIA';
export const DELETE_PICTURE = 'DELETE_PICTURE';

// Global error
export const APP_GLOBAL_ERROR = "APP_GLOBAL_ERROR";
export const CHANGE_APP_STATUS = "CHANGE_APP_STATUS";

export const GET_SESSIONS = "GET_SESSIONS";
export const GET_SESSION = "GET_SESSION";

export const SEND_COMMAND_REQUEST = "SKT_SEND_COMMAND";
export const SEND_COMMAND_RESPONSE = "TK_SEND_COMMAND_RESPONSE";
